# Generated by Django 5.2.10 on 2026-01-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
